### ISSUE TITLE
bosh_exporter crashes with  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by heikocane** [bosh-prometheus/bosh_exporter#27]
Hello,

I have started bosh exporter (fbosh_exporter, version 3.1.0 (branch: master, revision: c5769ed304fdf248aeb35b0c938150c01fdd001a) with the command 
```
bosh_exporter --bosh.url=10.176.220.6 --bosh.username=admin --bosh.password=mypassword --bosh.ca-cert-file=bosh_ca_cert.pem --metrics.environment=development --sd.filename=bosh_target_groups.json --web.listen-address=:9190 --bosh.log-level=DEBUG
```

The process is running, but when I access the /metrics endpoint I get an empty response and the process crashes with "panic: runtime error: invalid memory address or nil pointer dereference"

Here are the last lines of the output (log-level debug)
```
...
GET /info HTTP/1.1
Host: 10.176.220.6:25555
Authorization: [removed]

[director.clientRequest] 2019/03/12 07:34:30 DEBUG - Dumping Director client response:
HTTP/1.1 200 OK
Connection: close
Content-Length: 598
Content-Type: application/json
Date: Tue, 12 Mar 2019 06:34:30 GMT
Server: nginx
X-Content-Type-Options: nosniff

{"name":"bosh-director","uuid":"a53d9304-89b3-4b55-be6a-fdd9811a7f73","version":"268.4.0 (00000000)","user":"admin","cpi":"vsphere_cpi","stemcell_os":"ubuntu-xenial","stemcell_version":"170.9","user_authentication":{"type":"uaa","options":{"url":"https://10.176.220.6:8443","urls":["https://10.176.220.6:8443"]}},"features":{"local_dns":{"status":true},"power_dns":{"status":false,"extras":{"domain_name":"bosh"}},"compiled_package_cache":{"status":false,"extras":{"provider":null}},"snapshots":{"status":false},"config_server":{"status":true,"extras":{"urls":["https://10.176.220.6:8844/api/"]}}}}
INFO[0000] Using BOSH Director `bosh-director` (a53d9304-89b3-4b55-be6a-fdd9811a7f73)  source="bosh_exporter.go:282"
INFO[0000] Listening on :9190                            source="bosh_exporter.go:356"
[httpClient] 2019/03/12 07:34:38 DEBUG - Sending GET request to endpoint 'https://10.176.220.6:25555/deployments'
[attemptRetryStrategy] 2019/03/12 07:34:38 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2019/03/12 07:34:38 DEBUG - [requestID=3a6e2edf-e9bb-4aeb-6370-235893a3ff2b] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://10.176.220.6:25555/deployments' }
[director.clientRequest] 2019/03/12 07:34:39 DEBUG - Dumping Director client request:
GET /deployments HTTP/1.1
Host: 10.176.220.6:25555
Authorization: [removed]

[director.clientRequest] 2019/03/12 07:34:39 DEBUG - Dumping Director client response:
HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html;charset=utf-8
Date: Tue, 12 Mar 2019 06:34:39 GMT
Server: nginx
Vary: Accept-Encoding
Www-Authenticate: Basic realm="BOSH Director"
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

8e5
[{"name":"cf","teams":[],"cloud_config":"latest","stemcells":[{"name":"bosh-vsphere-esxi-ubuntu-xenial-go_agent","version":"250.9"}],"releases":[{"name":"binary-buildpack","version":"1.0.30"},{"name":"bosh-dns","version":"1.10.0"},{"name":"bosh-dns-aliases","version":"0.0.3"},{"name":"bpm","version":"1.0.3"},{"name":"capi","version":"1.77.0"},{"name":"cf-cli","version":"1.13.0"},{"name":"cf-networking","version":"2.22.0"},{"name":"cf-smoke-tests","version":"40.0.46"},{"name":"cf-syslog-drain","version":"9.1"},{"name":"cflinuxfs2","version":"1.272.0"},{"name":"cflinuxfs3","version":"0.66.0"},{"name":"credhub","version":"2.1.2"},{"name":"diego","version":"2.28.0"},{"name":"dotnet-core-buildpack","version":"2.2.5"},{"name":"garden-runc","version":"1.18.3"},{"name":"go-buildpack","version":"1.8.33"},{"name":"java-buildpack","version":"4.17.2"},{"name":"log-cache","version":"2.1.1"},{"name":"loggregator","version":"105.0"},{"name":"loggregator-agent","version":"3.7"},{"name":"mapfs","version":"1.1.4"},{"name":"nats","version":"26"},{"name":"nfs-volume","version":"2.0.2"},{"name":"nginx-buildpack","version":"1.0.8"},{"name":"node-exporter","version":"4.1.0"},{"name":"nodejs-buildpack","version":"1.6.43"},{"name":"php-buildpack","version":"4.3.70"},{"name":"pxc","version":"0.14.0"},{"name":"python-buildpack","version":"1.6.28"},{"name":"r-buildpack","version":"1.0.4"},{"name":"routing","version":"0.184.0"},{"name":"ruby-buildpack","version":"1.7.31"},{"name":"silk","version":"2.22.0"},{"name":"staticfile-buildpack","version":"1.4.39"},{"name":"statsd-injector","version":"1.7.0"},{"name":"uaa","version":"70.0"}]},{"name":"prometheus","teams":[],"cloud_config":"latest","stemcells":[{"name":"bosh-vsphere-esxi-ubuntu-xenial-go_agent","version":"170.13"}],"releases":[{"name":"bosh-dns","version":"1.10.0"},{"name":"bpm","version":"1.0.0"},{"name":"node-exporter","version":"4.1.0"},{"name":"postgres","version":"34"},{"name":"prometheus","version":"24.1.0"},{"name":"routing","version":"0.183.0"}]},{"name":"redis","teams":[],"cloud_config":"latest","stemcells":[{"name":"bosh-vsphere-esxi-ubuntu-trusty-go_agent","version":"3586.60"}],"releases":[{"name":"bosh-dns","version":"1.10.0"},{"name":"bpm","version":"1.0.0"},{"name":"redis","version":"15.2.3"}]}]
0

[httpClient] 2019/03/12 07:34:39 DEBUG - Sending GET request to endpoint 'https://10.176.220.6:25555/deployments/redis/instances?format=full'
[attemptRetryStrategy] 2019/03/12 07:34:39 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2019/03/12 07:34:39 DEBUG - [requestID=9718fb96-2511-49fb-4664-077051cc3e48] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://10.176.220.6:25555/deployments/redis/instances?format=full' }
[httpClient] 2019/03/12 07:34:39 DEBUG - Sending GET request to endpoint 'https://10.176.220.6:25555/deployments/cf/instances?format=full'
[attemptRetryStrategy] 2019/03/12 07:34:39 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[httpClient] 2019/03/12 07:34:39 DEBUG - Sending GET request to endpoint 'https://10.176.220.6:25555/deployments/prometheus/instances?format=full'
[clientRetryable] 2019/03/12 07:34:39 DEBUG - [requestID=9dac51b7-27df-4647-43b6-63f71d64bebd] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://10.176.220.6:25555/deployments/cf/instances?format=full' }
[attemptRetryStrategy] 2019/03/12 07:34:39 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2019/03/12 07:34:39 DEBUG - [requestID=d2d1f5ba-0f7e-4dd0-5b71-7f468caa76e8] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://10.176.220.6:25555/deployments/prometheus/instances?format=full' }
[httpClient] 2019/03/12 07:34:39 DEBUG - Sending POST request to endpoint 'https://10.176.220.6:8443/oauth/token'
[attemptRetryStrategy] 2019/03/12 07:34:39 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2019/03/12 07:34:39 DEBUG - [requestID=3e65bd71-75b6-4ec0-712d-8673e5ea5461] Requesting (attempt=1): Request{ Method: 'POST', URL: 'https://10.176.220.6:8443/oauth/token' }
[httpClient] 2019/03/12 07:34:39 DEBUG - Sending POST request to endpoint 'https://10.176.220.6:8443/oauth/token'
[attemptRetryStrategy] 2019/03/12 07:34:39 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2019/03/12 07:34:39 DEBUG - [requestID=dc62efe9-1db0-4180-71b6-097a31d1cd1e] Requesting (attempt=1): Request{ Method: 'POST', URL: 'https://10.176.220.6:8443/oauth/token' }
[httpClient] 2019/03/12 07:34:39 DEBUG - Sending POST request to endpoint 'https://10.176.220.6:8443/oauth/token'
[attemptRetryStrategy] 2019/03/12 07:34:39 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2019/03/12 07:34:39 DEBUG - [requestID=64306f49-43db-48a9-75fb-193dac05f883] Requesting (attempt=1): Request{ Method: 'POST', URL: 'https://10.176.220.6:8443/oauth/token' }
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x75456a]

goroutine 52 [running]:
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/uaa.(*AccessTokenSession).saveTokenCreds(0xc000057840, 0xc0001f8480, 0x464)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/uaa/access_token_session.go:56 +0x2a
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/uaa.(*AccessTokenSession).TokenFunc(0xc000057840, 0x101, 0x150, 0xc00030f760, 0x0, 0xc000186000)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/uaa/access_token_session.go:42 +0x10b
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/uaa.(*AccessTokenSession).TokenFunc-fm(0x1, 0x10, 0x10, 0x9387c0, 0x3c)
	/go/src/github.com/bosh-prometheus/bosh_exporter/bosh_exporter.go:249 +0x33
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.AuthRequestAdjustment.Adjust(0xc0001e62a0, 0x0, 0x0, 0x0, 0x0, 0xc00010f700, 0xc00031f801, 0xa09818, 0x7)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/auth_request_adjustment.go:40 +0x76
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.Factory.httpClient.func1(0xc00010f700, 0xc00000c730, 0x1, 0x1, 0xc000386080, 0x47)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/factory.go:69 +0xc1
net/http.(*Client).checkRedirect(0xc0001d9560, 0xc00010f700, 0xc00000c730, 0x1, 0x1, 0x0, 0x1)
	/usr/local/go/src/net/http/client.go:416 +0x60
net/http.(*Client).do(0xc0001d9560, 0xc00010f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:607 +0x8ba
net/http.(*Client).Do(0xc0001d9560, 0xc00010f200, 0xf, 0xa1db45, 0x2a)
	/usr/local/go/src/net/http/client.go:509 +0x35
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/httpclient.(*RequestRetryable).Attempt(0xc000308280, 0xa0f641, 0x14, 0xa127b1)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/httpclient/request_retryable.go:96 +0x20d
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/retrystrategy.(*attemptRetryStrategy).Try(0xc000229e80, 0xc000229e80, 0xc0002fc438)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/retrystrategy/attempt_retry_strategy.go:39 +0x176
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/httpclient.(*retryClient).Do(0xc000057980, 0xc00010f200, 0x0, 0x0, 0x0)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/httpclient/retry_clients.go:59 +0x1e1
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.AdjustableClient.Do(0x7f1432180110, 0xc000057980, 0xaa5b80, 0xc0001d9590, 0xc00010f200, 0x0, 0x0, 0x0)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/adjustable_client.go:49 +0x1c3
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/httpclient.(*HTTPClient).GetCustomized(0xc0000579c0, 0xc000270c80, 0x47, 0xc0002e54a0, 0xc0000579c0, 0xaa5bc0, 0xed24f8)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-utils/httpclient/http_client.go:130 +0x19a
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.ClientRequest.RawGet(0xc0001fe0e0, 0x1a, 0x0, 0x0, 0xc0000579c0, 0xaa5bc0, 0xed24f8, 0xaacb80, 0xc000136ac0, 0xc000302000, ...)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/client_request.go:105 +0x1ac
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.ClientRequest.Get(0xc0001fe0e0, 0x1a, 0x0, 0x0, 0xc0000579c0, 0xaa5bc0, 0xed24f8, 0xaacb80, 0xc000136ac0, 0xc000302000, ...)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/client_request.go:45 +0xe0
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.GetResult(0xc0001fe0e0, 0x1a, 0x0, 0x0, 0xc0000579c0, 0xaa5bc0, 0xed24f8, 0xaacb80, 0xc000136ac0, 0xaa71c0, ...)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:45 +0xbc
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.Client.deploymentResourceInfos(0xc0001fe0e0, 0x1a, 0x0, 0x0, 0xc0000579c0, 0xaa5bc0, 0xed24f8, 0xaacb80, 0xc000136ac0, 0xc0001fe0e0, ...)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/vms.go:131 +0x1e3
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.Client.DeploymentInstanceInfos(0xc0001fe0e0, 0x1a, 0x0, 0x0, 0xc0000579c0, 0xaa5bc0, 0xed24f8, 0xaacb80, 0xc000136ac0, 0xc0001fe0e0, ...)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/instances.go:40 +0x9b
github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director.DeploymentImpl.InstanceInfos(0xc0001fe0e0, 0x1a, 0x0, 0x0, 0xc0000579c0, 0xaa5bc0, 0xed24f8, 0xaacb80, 0xc000136ac0, 0xc0001fe0e0, ...)
	/go/src/github.com/bosh-prometheus/bosh_exporter/vendor/github.com/cloudfoundry/bosh-cli/director/instances.go:23 +0x80
github.com/bosh-prometheus/bosh_exporter/deployments.(*Fetcher).fetchDeploymentInstances(0xc0001d9da0, 0xab24c0, 0xc00014ac80, 0xc00003d788, 0x82f056, 0xc00003d6e0, 0x429e22, 0xc000000008)
	/go/src/github.com/bosh-prometheus/bosh_exporter/deployments/deployments_fetcher.go:82 +0x11d
github.com/bosh-prometheus/bosh_exporter/deployments.(*Fetcher).fetchDeploymentInfo(0xc0001d9da0, 0xab24c0, 0xc00014ac80, 0x8, 0xc000057380, 0xa9f6f0)
	/go/src/github.com/bosh-prometheus/bosh_exporter/deployments/deployments_fetcher.go:57 +0xa6
github.com/bosh-prometheus/bosh_exporter/deployments.(*Fetcher).Deployments.func1(0xc0001fb890, 0xc0001d9da0, 0xc0001fb888, 0xc000256300, 0xab24c0, 0xc00014ac80)
	/go/src/github.com/bosh-prometheus/bosh_exporter/deployments/deployments_fetcher.go:36 +0x87
created by github.com/bosh-prometheus/bosh_exporter/deployments.(*Fetcher).Deployments
	/go/src/github.com/bosh-prometheus/bosh_exporter/deployments/deployments_fetcher.go:34 +0x185
```

The credentials seems to work, I also use this credentials for connecting to bosh via bosh-cli.

I have the same problem when I use the bosh_exporter docker-image.

Any idea whtas wrong?

Thanks for your help

Heiko

**Comment by robertgmoss** [comment]
Hi Heiko,

Were you able to resolve this?  I'm getting the same error.

**Comment by robertgmoss** [comment]
Looking through the code, this line https://github.com/bosh-prometheus/bosh_exporter/blob/master/bosh_exporter.go#L249 appears to be the problem.  It passes in nil, but in https://github.com/cloudfoundry/bosh-cli/blob/master/uaa/access_token_session.go#L56 it tries to call a method on that nil value.

**Comment by frodenas** [comment]
Thanks @robertgmoss for the analysis. This should be fixed at https://github.com/bosh-prometheus/bosh_exporter/commit/8dce62dcf1659c3e205e9c742b4b4dc88afb60d7.
